import Config from './Config';
import type ProgressListenFunction from './ProgressListenFunction';
import ParseProgressReporter from './ParseProgressReporter';
import PdfParser from './PdfParser';
import PdfPipeline from './PdfPipeline';
import AdjustHeight from './transformer/AdjustHeight';
import UnwrapCoordinates from './transformer/UnwrapCoordinates';
import RemoveEmptyItems from './transformer/RemoveEmptyItems';
import CalculateStatistics from './transformer/CacluclateStatistics';
import CompactLines from './transformer/CompactLines';
import SortXWithinLines from './transformer/SortXWithinLines';
import RemoveRepetitiveItems from './transformer/RemoveRepetitiveItems';
import DetectToc from './transformer/DetectToc';
import NoOpTransformer from './transformer/NoOpTransformer';
export declare const transformers: (AdjustHeight | UnwrapCoordinates | RemoveEmptyItems | CalculateStatistics | CompactLines | SortXWithinLines | RemoveRepetitiveItems | DetectToc | NoOpTransformer)[];
export declare function pdfParser(pdfJs: any): PdfParser;
export declare function parseReporter(progressListener: ProgressListenFunction): ParseProgressReporter;
export declare function createPipeline(pdfJs: any, config?: Config): PdfPipeline;
