version: '3'

services:
  # web:
  #   image: node:latest
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - redis
  #     - postgres
  #   command: npm dev
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
