version: '3'

services:
  studio:
    image: node:18
    working_dir: /app/packages/db
    volumes:
      - .:/app
    ports:
      - '5555:5555'
    command: npx prisma studio
    environment:
      - DATABASE_URL=postgresql://example_user:example_password@postgres:5433/example_db?schema=public
  # langchain-tracing:
  #   build:
  #     context: .
  #     dockerfile: ./docker/python.Dockerfile
  #   working_dir: /app
  #   command: langchain-server
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PORT: 5433
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db

volumes:
  postgres_data:
  redis_data:
