version: '3'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '8288:8288'
    depends_on:
      - redis
      - postgres
    command: pnpm dev:turbo
  # inngest:
  #   image: node:latest
  #   # build:
  #   #   context: .
  #   #   dockerfile: apps/web/Dockerfile
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8288:8288'
  #   command: npm run dev-inngest
  #   depends_on:
  #     - web
  studio:
    image: node:latest
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '5555:5555'
    command: pnpm db:studio
    depends_on:
      - web
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db

volumes:
  postgres_data:
  redis_data:
